version: 1.0.{build}

configuration: Release

branches:
  only:
  - master
  
build:
  project: GarbageCollector.sln
  verbosity: minimal
  
artifacts:
  - name: Tests
    path: .\bin\v120\Win32\Release\unit-tests.exe

test_script:
  - cmd: .\bin\v120\Win32\Release\unit-tests.exe  --gtest_output=xml:unit-tests.xml

on_finish:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\bin\v120\Win32\Release\unit-tests.xml))
